Improvements to documentation
hiddenSymmetries/simsopt pull request #241
Opened 2022-06-25 16:31 UTC by landreman

This PR includes some improvements to the documentation:

- Fixed some links to the API docs that were not working in the docs after merging #239.
- Simplified more of the sub-submodule imports to submodule imports in the docs.
- In the coil optimization tutorial, the minimal example was simplified, and a new section was added to list the many available regularization terms.
- `stage_two_optimization.py` was split into a simpler minimal version and a version with all the regularization terms.

2022-06-25 17:12 UTC, mbkumar requested changes
Hello Matt,

Thanks for the fixes to the docs. Some of the classes such as Curve, Surface, ScaledSurface need not be exposed to the public. We can revert some of the changes in this PR.

2022-06-25 17:12 UTC, mbkumar commented on src/simsopt/field/__init__.py
>  from .magneticfieldclasses import *
I believe classes from magneticfield submodule need no exposure to public.

2022-06-25 17:12 UTC, mbkumar commented on src/simsopt/geo/curve.py
> +__all__ = ['Curve', 'RotatedCurve', 'curves_to_vtk', 'create_equally_spaced_curves']
Curve on its own is not usable. So public exposure is not needed.

2022-06-25 17:12 UTC, mbkumar commented on src/simsopt/geo/surface.py
> +
Again my suggestion is not to expose Surface and SurfaceScaled to end users.

2022-06-25 18:10 UTC, landreman commented
I agree that the base classes `Curve`, `Surface`, and `MagneticField` aren't user-facing so we shouldn't need to import them into `simsopt.geo` and `simsopt.field` in principle. However, when I tried this approach, I experienced two problems. First, then `Curve`, `Surface`, and `MagneticField` don't appear anywhere in the API docs, not even in the more detailed API docs "for developers". This is a problem because then some important user-facing methods like `.plot()` and `.to_vtk()` aren't in the API docs anywhere. Second, if `Curve`, `Surface`, and `MagneticField` aren't imported into `simsopt.geo` and `simsopt.field`, then it doesn't seem possible to link to these classes in the `.rst` docs files. For instance, in this approach, then where `:obj:'simsopt.geo.curve.Curve'` appears in one of the `.rst` files, the hyperlink to the developer API docs does not work. Do you see some other way around these problems?

2022-06-25 19:29 UTC, mbkumar commented
Ok.  Makes sense. In that case your changes are correct.

On Sat, Jun 25, 2022, 2:10 PM Matt Landreman ***@***.***>
wrote:

> I agree that the base classes Curve, Surface, and MagneticField aren't
> user-facing so we shouldn't need to import them into simsopt.geo and
> simsopt.field in principle. However, when I tried this approach, I
> experienced two problems. First, then Curve, Surface, and MagneticField
> don't appear anywhere in the API docs, not even in the more detailed API
> docs "for developers". This is a problem because then some important
> user-facing methods like .plot() and .to_vtk() aren't in the API docs
> anywhere. Second, if Curve, Surface, and MagneticField aren't imported
> into simsopt.geo and simsopt.field, then it doesn't seem possible to link
> to these classes in the .rst docs files. For instance, in this approach,
> then where :obj:'simsopt.geo.curve.Curve' appears in one of the .rst
> files, the hyperlink to the developer API docs does not work. Do you see
> some other way around these problems?
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/hiddenSymmetries/simsopt/pull/241#issuecomment-1166336647>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AA62VECAJYFQE7QB3WCMFGDVQ5DQ3ANCNFSM5Z2QSYFA>
> .
> You are receiving this because your review was requested.Message ID:
> ***@***.***>
>

2022-06-27 01:07 UTC, mbkumar approved these changes

2022-06-27 01:07 UTC, merged