clear spec cache to avoid sporadic mismatch
hiddenSymmetries/simsopt pull request #431
Opened 2024-06-27 08:28 UTC by smiet

Should fix the sporadic failure in the CI #357

The issue: f90wrap uses getter and setters to access the F90wrapped FORTRAN arrays, and the logic is as follows: 
```Python
handle = get_specific_array_handle(stuff)  #pointer to the array
if handle in self._arrays #dict with arrays and handles:
  return self._arrays[handle]
else:
  array = get_array_in_complicated_f90wrapway(stuff)
  self._arrays[handle]=array
  return array
```

Now for the race condition: If spec has run before, and the array has been accessed before (put in cache), and *by happenstance* the handle remains the same, python will return the cached array, and not access the FORTRAN memory. 

The handle is basically the pointer to the array, cast as an int. It is unlikely to be exactly the same EXCEPT when a conveniently shaped hole has just been emptied in memory by deallocation. 

This also explains why the fault is mostly seen in CI, as they have much smaller memories, and are more likely to write to the same location. But this is handled by the CPU and not reproducible.

2024-06-27 12:03 UTC, andrewgiuliani commented
I don't see how this is a race condition. We don't have multiple cores modifying the same area of memory here, do we?

Wouldn't self._arrays[handle] be out of bounds or return a not found exception if the handle is not in _arrays?

2024-06-28 11:50 UTC, smiet commented
@andrewgiuliani you are right, this is not a race condition, excuse my ignorance. 

F90wrap works in a funny way (I don't completely understand it), but the cache is only cleared when the python kernel quits. It sets up links to shared FORTRAN memory that persist until the kernel exits.

Normally you only run a single simulation, and the kernel quits when the optimisation has finished, it is only in testing that many many many SPEC instances are created and destroyed. 

For example in
```
from simsopt.mhd import Spec
myspec1 = Spec('firstfile.sp')
myspec2 = Spec('differentfile.sp')

print(myspec1.allglobal.ext)
>>> differentfile
```
the Fortran arrays in myspec1 and myspec2 are the same. 

This is a limitation of f90wrap and the above code should not be used. The best we can do is make sure that loading a new state runs correctly. 

Yes this is a memory leak when many Spec objects are initialized in the same kernel session, but I don't see how to avoid it.

2024-06-28 18:26 UTC, andrewgiuliani commented
When you clear the cache, is it possible to run a call on the FORTRAN side to deallocate the allocated arrays referenced in the cache?

If not, I would suggest that this anomalous behaviour should be mentioned in a docstring somewhere.

2024-06-28 18:33 UTC, andrewgiuliani requested changes
see above for comments

2024-06-28 18:51 UTC, smiet commented
@andrewgiuliani This is not possible with the current implementation of f90wrap, and I am not sure if desired. It is meant to wrap existing programs, giving you access to the memory as they run, with the possibility of muting existing arrays. Forcing deallocation on the FORTRAN side from the python side would alter the program it is wrapping. 

It is certainly a bug in the implementation that a handle collission (that is the right term!) is likely to occur, if arrays are deallocated and immediately afterwards allocated on memory-constrained systems, but this is at the core of some design choices made for f90wrap, and not something I feel comfortable fixing. 

The current PR fixes the anomalous behavior that was occurring (that the cache kept accumulating), and this fix, though a bit draconian, prevents such behavior (and since the collision could occur for every accessed array, it is the right thing to do).

I will probably open an issue on the upstream f90wrap, but this will take a while as the whole numpy2.0 migration has left me very little time for science, and I have some QUASR configurations to calculate tangles in! ;)

2024-06-28 23:42 UTC, andrewgiuliani commented
I would have thought that a deallocate all function could be written in on the Fortran side and called from python.

In any case I think that this is great that the bug has been identified!

2024-06-29 13:54 UTC, mbkumar commented
@smiet , can we have a zoom call to understand what is going on? I am not getting the full picture from your description.

2024-06-29 14:01 UTC, mbkumar commented
At the least can you talk to the f90wrap developer, who might have encountered this issue before? There should be some mechanism in f90wrap to clear the cache.

2024-06-30 19:52 UTC, smiet commented
@mbkumar yes, let's zoom tomorrow (Monday), was away from internet this weekend. Can you set it up? I'm having a little trouble with email on my phone right now, available all your morning

2024-06-30 19:54 UTC, andrewgiuliani commented
I'd like to be present during the zoom too to better understand the problem

2024-07-03 15:30 UTC, smiet commented
Some notes of the discussion resulted in issue  #434. 

All tests are passing consistently, this PR doesn't solve the root cause, but it applies a fix to stop a known bug. I suggest we move further discussion of this topic to #434 and merge this fix so we can stop seeing sporadic failures in our CI. @mbkumar @landreman @andrewgiuliani

2024-07-03 15:57 UTC, landreman approved these changes
Thanks for figuring out a fix for this tricky bug!

2024-07-03 20:57 UTC, andrewgiuliani approved these changes

2024-07-03 21:24 UTC, merged